export const areas = [
  { id: "Busaiteen", name: "Busaiteen" },
  { id: "Hidd", name: "Hidd" },
  { id: "Al Dair", name: "Al Dair" },
  { id: "Al Sayh", name: "Al Sayh" },
  { id: "Muharraq", name: "Muharraq" },
  { id: "Amwaj", name: "Amwaj" },
  { id: "Halat Seltah", name: "Halat Seltah" },
  { id: "Halat Naim", name: "Halat Naim" },
  { id: "Samaheej", name: "Samaheej" },
  { id: "Arad", name: "Arad" },
  { id: "Galaly", name: "Galaly" },
  { id: "Al Burhama", name: "Al Burhama" },
  { id: "Zinj", name: "Zinj" },
  { id: "Seef", name: "Seef" },
  { id: "Salihiya", name: "Salihiya" },
  { id: "AlJuffair", name: "AlJuffair" },
  { id: "Al Hoora", name: "Al Hoora" },
  { id: "Sagaya", name: "Sagaya" },
  { id: "Alsalmaniya", name: "Alsalmaniya" },
  { id: "Alsuwayfiyah", name: "Alsuwayfiyah" },
  { id: "Adliya", name: "Adliya" },
  { id: "Alghurayfah", name: "Alghurayfah" },
  { id: "Alfateh", name: "Alfateh" },
  { id: "Qudaibiya", name: "Qudaibiya" },
  { id: "Alguful", name: "Alguful" },
  { id: "Alcorniche", name: "Alcorniche" },
  { id: "Mahooz", name: "Mahooz" },
  { id: "Alnaim", name: "Alnaim" },
  { id: "Sea Front City Center", name: "Sea Front City Center" },
  { id: "Umm Al Hassam", name: "Umm Al Hassam" },
  { id: "Bu Ashira", name: "Bu Ashira" },
  { id: "Bu Ghazal", name: "Bu Ghazal" },
  { id: "Diplomatic Area", name: "Diplomatic Area" },
  { id: "Nabih Saleh", name: "Nabih Saleh" },
  { id: "Bilad Al Qadeem", name: "Bilad Al Qadeem" },
  { id: "Sanabis", name: "Sanabis" },
  { id: "Karbabad", name: "Karbabad" },
  { id: "Manama Center", name: "Manama Center" },
  { id: "Abu Saiba", name: "Abu Saiba" },
  { id: "Budaiya", name: "Budaiya" },
  { id: "Al Jasra", name: "Al Jasra" },
  { id: "Al Janabiyah", name: "Al Janabiyah" },
  { id: "Khamis", name: "Khamis" },
  { id: "Diraz", name: "Diraz" },
  { id: "Daih", name: "Daih" },
  { id: "South Sehla", name: "South Sehla" },
  { id: "North Sehla", name: "North Sehla" },
  { id: "Shakhurah", name: "Shakhurah" },
  { id: "Al Safriyah", name: "Al Safriyah" },
  { id: "Al Qadam", name: "Al Qadam" },
  { id: "Al Qurayyah", name: "Al Qurayyah" },
  { id: "Al Qalah", name: "Al Qalah" },
  { id: "Al Lawzi", name: "Al Lawzi" },
  { id: "Malkiya", name: "Malkiya" },
  { id: "Salman City", name: "Salman City" },
  { id: "Al Markh", name: "Al Markh" },
  { id: "Al Musalla", name: "Al Musalla" },
  { id: "Hamala", name: "Hamala" },
  { id: "Barbar", name: "Barbar" },
  { id: "Bani Jamra", name: "Bani Jamra" },
  { id: "Bu Quwah", name: "Bu Quwah" },
  { id: "Buri", name: "Buri" },
  { id: "Jeblat Hebshi", name: "Jeblat Hebshi" },
  { id: "Jid Al Haj", name: "Jid Al Haj" },
  { id: "Jidhafs", name: "Jidhafs" },
  { id: "Jannusan", name: "Jannusan" },
  { id: "Hillat Abdul Saleh", name: "Hillat Abdul Saleh" },
  { id: "Damistan", name: "Damistan" },
  { id: "Saar", name: "Saar" },
  { id: "Shahrakkan", name: "Shahrakkan" },
  { id: "Sadad", name: "Sadad" },
  { id: "Tashan", name: "Tashan" },
  { id: "Adhari - Abu-Baham", name: "Adhari - Abu-Baham" },
  { id: "Karranah", name: "Karranah" },
  { id: "Karzakkan", name: "Karzakkan" },
  { id: "Madinat Hamad Hamad Town", name: "Madinat Hamad Hamad Town" },
  { id: "Maqabah", name: "Maqabah" },
  { id: "Sanad", name: "Sanad" },
  { id: "Sitra Industrial Area", name: "Sitra Industrial Area" },
  { id: "Al Bahair", name: "Al Bahair" },
  { id: "Jurdab", name: "Jurdab" },
  { id: "Sitra Murqoban", name: "Sitra Murqoban" },
  { id: "Sitra Wadiyan", name: "Sitra Wadiyan" },
  { id: "Ma`ameer", name: "Ma`ameer" },
  { id: "Sitra Mahaza", name: "Sitra Mahaza" },
  { id: "Bu Kowarah", name: "Bu Kowarah" },
  { id: "Isa Town", name: "Isa Town" },
  {
    id: "Riffa Alshamali North Riffa",
    name: "Riffa Alshamali North Riffa",
  },
  { id: "Tubli", name: "Tubli" },
  { id: "Sitra Sufala", name: "Sitra Sufala" },
  { id: "Sitra Al Qaryah", name: "Sitra Al Qaryah" },
  {
    id: "Sitra Al Hamriyah Sitra Mall",
    name: "Sitra Al Hamriyah Sitra Mall",
  },
  { id: "Sitra Abu Alayash", name: "Sitra Abu Alayash" },
  { id: "Al Eker", name: "Al Eker" },
  { id: "Zayed Town", name: "Zayed Town" },
  { id: "Nuwaidrat", name: "Nuwaidrat" },
  { id: "Salmabad", name: "Salmabad" },
  { id: "Jary Al Shaikh", name: "Jary Al Shaikh" },
  { id: "Jid Ali", name: "Jid Ali" },
  { id: "Sitra Al Kharijiya", name: "Sitra Al Kharijiya" },
  { id: "Sitra Um Al Baidh", name: "Sitra Um Al Baidh" },
  { id: "Alhajiyat", name: "Alhajiyat" },
  { id: "Hoarat A'ali", name: "Hoarat A'ali" },
  { id: "A'ali", name: "A'ali" },
  { id: "Alhunayniyah", name: "Alhunayniyah" },
  { id: "East Riffa", name: "East Riffa" },
  { id: "West Riffa", name: "West Riffa" },
  { id: "Wadi AlSail", name: "Wadi AlSail" },
  { id: "Sakhir", name: "Sakhir" },
  { id: "Al Mazrowiah", name: "Al Mazrowiah" },
  {
    id: "Jazaair Beach Bilag Al Jazaair",
    name: "Jazaair Beach Bilag Al Jazaair",
  },
  { id: "Jaww", name: "Jaww" },
  { id: "Durrat Al Bahrain", name: "Durrat Al Bahrain" },
  { id: "Safreh", name: "Safreh" },
  { id: "Askar", name: "Askar" },
  { id: "Awali", name: "Awali" },
  { id: "Zallaq", name: "Zallaq" },
  { id: "Riffa Views", name: "Riffa Views" },
  { id: "Dar Kulaib", name: "Dar Kulaib" },
  { id: "Bahrain Financial Harbour", name: "Bahrain Financial Harbour" },
  { id: "Ras Rumman", name: "Ras Rumman" },
  { id: "Mina Salman", name: "Mina Salman" },
  { id: "Al Maqsha", name: "Al Maqsha" },
  { id: "Alareen", name: "Alareen" },
  { id: "Askar Alba", name: "Askar Alba" },
  { id: "Bahrain Bay", name: "Bahrain Bay" },
  { id: "Diyar Al Muharraq", name: "Diyar Al Muharraq" },
  { id: "Hidd Industrial Area", name: "Hidd Industrial Area" },
  { id: "Reef Island", name: "Reef Island" },
  { id: "Sakhir Camping Zone A", name: "Sakhir Camping Zone A" },
  { id: "Sakhir Camping Zone B", name: "Sakhir Camping Zone B" },
  { id: "Sakhir Camping Zone C", name: "Sakhir Camping Zone C" },
  { id: "Sakhir Camping Zone D", name: "Sakhir Camping Zone D" },
  { id: "Sakhir Industial 2", name: "Sakhir Industial 2" },
  { id: "Khalifa Town", name: "Khalifa Town" },
  { id: "Al Dur", name: "Al Dur" },
  { id: "Dilmunia Island", name: "Dilmunia Island" },
  { id: "Sakhir Industrial 3", name: "Sakhir Industrial 3" },
];

function compare(a, b) {
  if (a.name < b.name) {
    return -1;
  }
  if (a.name > b.name) {
    return 1;
  }
  return 0;
}

areas.sort(compare);
