export const areas = [
  { label: "Busaiteen", value: "Busaiteen" },
  { label: "Hidd", value: "Hidd" },
  { label: "Al Dair", value: "Al Dair" },
  { label: "Al Sayh", value: "Al Sayh" },
  { label: "Muharraq", value: "Muharraq" },
  { label: "Amwaj", value: "Amwaj" },
  { label: "Halat Seltah", value: "Halat Seltah" },
  { label: "Halat Naim", value: "Halat Naim" },
  { label: "Samaheej", value: "Samaheej" },
  { label: "Arad", value: "Arad" },
  { label: "Galaly", value: "Galaly" },
  { label: "Al Burhama", value: "Al Burhama" },
  { label: "Zinj", value: "Zinj" },
  { label: "Seef", value: "Seef" },
  { label: "Salihiya", value: "Salihiya" },
  { label: "AlJuffair", value: "AlJuffair" },
  { label: "Al Hoora", value: "Al Hoora" },
  { label: "Sagaya", value: "Sagaya" },
  { label: "Alsalmaniya", value: "Alsalmaniya" },
  { label: "Alsuwayfiyah", value: "Alsuwayfiyah" },
  { label: "Adliya", value: "Adliya" },
  { label: "Alghurayfah", value: "Alghurayfah" },
  { label: "Alfateh", value: "Alfateh" },
  { label: "Qudaibiya", value: "Qudaibiya" },
  { label: "Alguful", value: "Alguful" },
  { label: "Alcorniche", value: "Alcorniche" },
  { label: "Mahooz", value: "Mahooz" },
  { label: "Alnaim", value: "Alnaim" },
  { label: "Sea Front City Center", value: "Sea Front City Center" },
  { label: "Umm Al Hassam", value: "Umm Al Hassam" },
  { label: "Bu Ashira", value: "Bu Ashira" },
  { label: "Bu Ghazal", value: "Bu Ghazal" },
  { label: "Diplomatic Area", value: "Diplomatic Area" },
  { label: "Nabih Saleh", value: "Nabih Saleh" },
  { label: "Bilad Al Qadeem", value: "Bilad Al Qadeem" },
  { label: "Sanabis", value: "Sanabis" },
  { label: "Karbabad", value: "Karbabad" },
  { label: "Manama Center", value: "Manama Center" },
  { label: "Abu Saiba", value: "Abu Saiba" },
  { label: "Budaiya", value: "Budaiya" },
  { label: "Al Jasra", value: "Al Jasra" },
  { label: "Al Janabiyah", value: "Al Janabiyah" },
  { label: "Khamis", value: "Khamis" },
  { label: "Diraz", value: "Diraz" },
  { label: "Daih", value: "Daih" },
  { label: "South Sehla", value: "South Sehla" },
  { label: "North Sehla", value: "North Sehla" },
  { label: "Shakhurah", value: "Shakhurah" },
  { label: "Al Safriyah", value: "Al Safriyah" },
  { label: "Al Qadam", value: "Al Qadam" },
  { label: "Al Qurayyah", value: "Al Qurayyah" },
  { label: "Al Qalah", value: "Al Qalah" },
  { label: "Al Lawzi", value: "Al Lawzi" },
  { label: "Malkiya", value: "Malkiya" },
  { label: "Salman City", value: "Salman City" },
  { label: "Al Markh", value: "Al Markh" },
  { label: "Al Musalla", value: "Al Musalla" },
  { label: "Hamala", value: "Hamala" },
  { label: "Barbar", value: "Barbar" },
  { label: "Bani Jamra", value: "Bani Jamra" },
  { label: "Bu Quwah", value: "Bu Quwah" },
  { label: "Buri", value: "Buri" },
  { label: "Jeblat Hebshi", value: "Jeblat Hebshi" },
  { label: "Jid Al Haj", value: "Jid Al Haj" },
  { label: "Jidhafs", value: "Jidhafs" },
  { label: "Jannusan", value: "Jannusan" },
  { label: "Hillat Abdul Saleh", value: "Hillat Abdul Saleh" },
  { label: "Damistan", value: "Damistan" },
  { label: "Saar", value: "Saar" },
  { label: "Shahrakkan", value: "Shahrakkan" },
  { label: "Sadad", value: "Sadad" },
  { label: "Tashan", value: "Tashan" },
  { label: "Adhari - Abu-Baham", value: "Adhari - Abu-Baham" },
  { label: "Karranah", value: "Karranah" },
  { label: "Karzakkan", value: "Karzakkan" },
  { label: "Madinat Hamad Hamad Town", value: "Madinat Hamad Hamad Town" },
  { label: "Maqabah", value: "Maqabah" },
  { label: "Sanad", value: "Sanad" },
  { label: "Sitra Industrial Area", value: "Sitra Industrial Area" },
  { label: "Al Bahair", value: "Al Bahair" },
  { label: "Jurdab", value: "Jurdab" },
  { label: "Sitra Murqoban", value: "Sitra Murqoban" },
  { label: "Sitra Wadiyan", value: "Sitra Wadiyan" },
  { label: "Ma`ameer", value: "Ma`ameer" },
  { label: "Sitra Mahaza", value: "Sitra Mahaza" },
  { label: "Bu Kowarah", value: "Bu Kowarah" },
  { label: "Isa Town", value: "Isa Town" },
  {
    label: "Riffa Alshamali North Riffa",
    value: "Riffa Alshamali North Riffa",
  },
  { label: "Tubli", value: "Tubli" },
  { label: "Sitra Sufala", value: "Sitra Sufala" },
  { label: "Sitra Al Qaryah", value: "Sitra Al Qaryah" },
  {
    label: "Sitra Al Hamriyah Sitra Mall",
    value: "Sitra Al Hamriyah Sitra Mall",
  },
  { label: "Sitra Abu Alayash", value: "Sitra Abu Alayash" },
  { label: "Al Eker", value: "Al Eker" },
  { label: "Zayed Town", value: "Zayed Town" },
  { label: "Nuwaidrat", value: "Nuwaidrat" },
  { label: "Salmabad", value: "Salmabad" },
  { label: "Jary Al Shaikh", value: "Jary Al Shaikh" },
  { label: "Jid Ali", value: "Jid Ali" },
  { label: "Sitra Al Kharijiya", value: "Sitra Al Kharijiya" },
  { label: "Sitra Um Al Baidh", value: "Sitra Um Al Baidh" },
  { label: "Alhajiyat", value: "Alhajiyat" },
  { label: "Hoarat A'ali", value: "Hoarat A'ali" },
  { label: "A'ali", value: "A'ali" },
  { label: "Alhunayniyah", value: "Alhunayniyah" },
  { label: "East Riffa", value: "East Riffa" },
  { label: "West Riffa", value: "West Riffa" },
  { label: "Wadi AlSail", value: "Wadi AlSail" },
  { label: "Sakhir", value: "Sakhir" },
  { label: "Al Mazrowiah", value: "Al Mazrowiah" },
  {
    label: "Jazaair Beach Bilag Al Jazaair",
    value: "Jazaair Beach Bilag Al Jazaair",
  },
  { label: "Jaww", value: "Jaww" },
  { label: "Durrat Al Bahrain", value: "Durrat Al Bahrain" },
  { label: "Safreh", value: "Safreh" },
  { label: "Askar", value: "Askar" },
  { label: "Awali", value: "Awali" },
  { label: "Zallaq", value: "Zallaq" },
  { label: "Riffa Views", value: "Riffa Views" },
  { label: "Dar Kulaib", value: "Dar Kulaib" },
  { label: "Bahrain Financial Harbour", value: "Bahrain Financial Harbour" },
  { label: "Ras Rumman", value: "Ras Rumman" },
  { label: "Mina Salman", value: "Mina Salman" },
  { label: "Al Maqsha", value: "Al Maqsha" },
  { label: "Alareen", value: "Alareen" },
  { label: "Askar Alba", value: "Askar Alba" },
  { label: "Bahrain Bay", value: "Bahrain Bay" },
  { label: "Diyar Al Muharraq", value: "Diyar Al Muharraq" },
  { label: "Hidd Industrial Area", value: "Hidd Industrial Area" },
  { label: "Reef Island", value: "Reef Island" },
  { label: "Sakhir Camping Zone A", value: "Sakhir Camping Zone A" },
  { label: "Sakhir Camping Zone B", value: "Sakhir Camping Zone B" },
  { label: "Sakhir Camping Zone C", value: "Sakhir Camping Zone C" },
  { label: "Sakhir Camping Zone D", value: "Sakhir Camping Zone D" },
  { label: "Sakhir Industial 2", value: "Sakhir Industial 2" },
  { label: "Khalifa Town", value: "Khalifa Town" },
  { label: "Al Dur", value: "Al Dur" },
  { label: "Dilmunia Island", value: "Dilmunia Island" },
  { label: "Sakhir Industrial 3", value: "Sakhir Industrial 3" },
];
